Update patch set 1
Patch Set 1:

studio-1.0-dev doesn't seem to be available in idea repo. I am getting this error when I do a sync:

error: in `sync`: revision studio-1.0-dev in platform/tools/idea not found

I put this change in a studio-1.0-dev branch yesterday and repo uploads were failing. 

What branch should I put this cl in?
Thanks.

Patch-set: 1
Reviewer: Gerrit User 1030953 <1030953@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0